### ISSUE TITLE
Problems with sequence matcher

### ISSUE THREAD

**Issue by 20milliliter** [Pyxus/fray#43] opened 2023-03-23 00:38 UTC
I'm currently building movement composites as follows:

```gdscript
func _ready():

	FrayInputMap.add_bind_action("left", "left")
	FrayInputMap.add_bind_action("right", "right")
	FrayInputMap.add_bind_action("up", "up")
	FrayInputMap.add_bind_action("down", "down")

	FrayInputMap.add_composite_input("forward", FrayConditionalInput.builder()
		.add_component("", FrayCombinationInput.builder()
			.add_component(FraySimpleInput.from_bind("right"))
			.mode_async()
			.build()
		)
		.add_component("on_right", FrayCombinationInput.builder()
			.add_component(FraySimpleInput.from_bind("left"))
			.mode_async()
			.is_virtual()
			.build()
		)
		.build()
	)

	FrayInputMap.add_composite_input("back", FrayConditionalInput.builder()
		.add_component("", FrayCombinationInput.builder()
			.add_component(FraySimpleInput.from_bind("left"))
			.mode_async()
			.build()
		)
		.add_component("on_right", FrayCombinationInput.builder()
			.add_component(FraySimpleInput.from_bind("right"))
			.mode_async()
			.is_virtual()
			.build()
		)
		.build()
	)

	FrayInputMap.add_composite_input("forward_up", FrayCombinationInput.builder()
		.add_component(FrayInputMap.get_composite_input("forward"))
		.add_component(FraySimpleInput.from_bind("up"))
		.mode_async()
		.is_virtual()
		.build()
	)

	FrayInputMap.add_composite_input("forward_down", FrayCombinationInput.builder()
		.add_component(FrayInputMap.get_composite_input("forward"))
		.add_component(FraySimpleInput.from_bind("down"))
		.mode_async()
		.is_virtual()
		.build()
	)
```

as well as simply displaying the `FrayInputEvent` from `_on_FrayInput_input_detected`.

This is the result:
![sad](https://user-images.githubusercontent.com/107726700/227069194-ee703628-b23b-428f-9eaa-43ddee92df30.gif)

Sometimes the composite input will be ignored and only one of the components registered.
Of course, attempting to match sequences fails as erroneous inputs are being fed into the analyzer.

~~Is this a bug or is there a `is_virtual()` somewhere there shouldn't be?~~

**Comment by 20milliliter** [comment] 2023-03-23 00:44
I tried removing all the `virtual()` calls and the issue persists.

**Comment by Pyxus** [comment] 2023-03-23 04:19
That's irritating... I believe I know the issue but I thought it had long since been resolved. An early commit must of caused a regression. That's for bringing this up, i'll look into it. The API has more or less stabilized so the plan is to iron everything out and release before the end of the month as my time will be shrinking again shortly.

**Comment by 20milliliter** [comment] 2023-03-23 13:03
Sounds good, I'll try to be as active as possible to test and report stuff to help make that happen.

**Comment by Pyxus** [comment] 2023-03-25 14:53
An update on this. The input manager does not emit a continuous signal for held inputs. This behavior is not a limitation of Godot but rather a design decision that I intentionally made in the past. However, I'm currently unsure of the reasoning behind this decision. Although Godot's `_input()` method also exhibits the same behavior, I suspect I had additional reasons for implementing this design choice beyond replicating that.

Nevertheless, a straightforward "fix" for the issue is to check if the event is just pressed and distinct. You can accomplish this by implementing the following code:

```
func(ev: FrayInputEvent):
	if ev.is_just_pressed() and ev.is_distinct():
		label.text = ev.input
```

Given that the sequence matcher is designed to work with discrete inputs, filtering them out through this method seems to be the best approach. I'll leave this issue open as it is technically not resolved. But I think all this really calls for is tweaks to the documentation.

**Comment by 20milliliter** [comment] 2023-03-25 16:39
I'm still experiencing a couple of matching issues.
Firstly, diagonal composites:

- 47A matches as expected.
- 74A matches as expected.
- 87A matches as 7A, 47A, or 4A.
- 69A matches as expected.
- 98A matches as expected.
- 89A matches as 9A, 69A, or 6A.

Secondly, shared charged input:

-  `.first("attack")`
- `.first("attack", 750)`

The matcher actually handles both as expected when without the discretion check, however of course leaving it out is not exactly a solution.

**Comment by 20milliliter** [comment] 2023-03-26 02:13
Printing `FrayInputEvent`s as they are active, in the order they are received:

![first](https://user-images.githubusercontent.com/107726700/227751497-6412c915-05f3-4996-aaba-1916ad0481f8.gif)

**Comment by 20milliliter** [comment] 2023-03-26 02:21
Found the issue.

```gdscript
FrayInputMap.add_composite_input("forward_up", FrayCombinationInput.builder()
	.add_component(FrayInputMap.get_composite_input("forward"))
	.add_component(FraySimpleInput.from_bind("up"))
	.mode_async()
	.is_virtual()
	.build()
)
```

Any word on why `get_composite_input()` doesn't work here?

**Comment by 20milliliter** [comment] 2023-03-26 02:47
...and back to not knowing for sure.

![second](https://user-images.githubusercontent.com/107726700/227752362-0cf5c98f-7f95-44c3-a160-58475a7a0572.gif)

Doesn't help that the [example](https://github.com/Pyxus/fray/blob/main/docs/getting_started/mod_input/index.md) is not even close to correct. What needs to be virtual?

**Comment by 20milliliter** [comment] 2023-03-26 03:03
Whatever, going with just `"left"` and `"right"` `FraySimpleInput.from_bind()`s to proceed.

I'm now unable to get _any_ response from a charged input.
`.first("attack", 0).build()` works, `.first("attack", 1).build()` does not.

`.enable_negative_edge()` does not appear to be working as intended either.

**Comment by Pyxus** [comment] 2023-03-27 22:08
> I'm still experiencing a couple of matching issues.

Another update on this. My original "fix" was misguided. I haven't viewed the matcher's code in a while so I was misunderstanding the way it behaved. The matcher already automatically ignores non-distinct inputs, and echo inputs. It also accepts both pressed and released inputs with some logic to prevent release inputs from causing problems so feeding only pressed inputs to it is unnecessary.

I believe the reason for the breaks in your previous test is that the wrong composite inputs are being flagged as distinct. Whether a composite is considered distinct is based on a "first come first served" approach since multiple composites can use the same binds. Try giving the more complex composites a higher priority. Priority is my attempt to keep the matcher flexible in a way that isn't tedious to setup like having the user manually set inputs to ignore.

Here is an example of what I mean:

```gdscript
	FrayInputMap.add_composite_input("forward_up", FrayCombinationInput.builder()
		.add_component(FrayInputMap.get_composite_input("forward"))
		.add_component(FraySimpleInput.from_bind("up"))
		.mode_async()
		.priority(5)
		.is_virtual()
		.build()
	)
```

I've tested 47, 74, 87, 69, 98, 89, 236, 23698, 698, 69874, 874, 412, 46
successfully

> Secondly, shared charged input:

Still looking in to what's going with charged inputs... May have to spend this weekend reviewing the matcher as you've brought to light how inconsistently its been behaving,

> Any word on why get_composite_input() doesn't work here?

I actually hadn't thought to use that method like this until having seen your code. I don't know why it would cause any issue but this is sort of untested so i'll have to look into it.

> .enable_negative_edge() does not appear to be working as intended either.

Appears to work fine for me. May just be a result of the bad example I gave you which prevented released inputs from being fed into the matcher.

Checkout this PR for the most recent tweaks to the matcher: #46

**Comment by Pyxus** [comment] 2023-03-27 22:32
Renaming as it appears to me that these issues are mostly related to flaws in the sequence matcher / related documentation.

**Comment by 20milliliter** [comment] 2023-03-27 23:57
> Try giving the more complex composites a higher priority

Motion inputs now appear to work correctly.  Thanks.

---

Charged inputs also work again, but the issue with a shared binding persists. 

I do actually have an idea for a work-around, but don't want to go off of any current behavior as you seem to think there's many issues.

---

> Appears to work fine for me

Still not for me. Maybe I'm misunderstanding how they function.

```gdscript
sequence_tree.add("PK_negative", FraySequenceBranch.builder()
	.first("punch")
	.then("kick")
	.enable_negative_edge()
	.build()
)
```

How I perceive this sequence is as follows:

![image](https://user-images.githubusercontent.com/107726700/228092366-0708a47d-9059-49f7-9dc3-0b6bd50c34ed.png)

---

>  I've added a warning now

Thanks!

**Comment by 20milliliter** [comment] 2023-03-28 15:04
> Maybe I'm misunderstanding how they function.

After taking a second look, the issue I was having was inconsistency in how negative edge sequences are declared.

Suppose a sequence `.first("P").then("K").enable_negative_edge()`. 
This sequence represented as a character string is actually `"KP"`, a different order than how its declared in the chain.
That's the point, of course: negative edge _means_ you open with the last input. 
I personally don't like this, though.

Suppose we instead represent the sequence with this hypothetical character string, `"PK^"`, with the `^` indicating the release of the first button in the sequence. I find myself envisioning this version of the string when I read the method chain. 
You press `P` first.
Of course, the issue is that the inputs aren't actually in this order.

What are your thoughts on adding functionality to reorder the inputs on an `enable_negative_edge()` call?

To clarify, this would probably not override the current behavior (as I assume it's a result of how discussion/notation handles negative edge within the FGC already, and my alternate perception is only due to my unfamiliarity with the mechanic), instead being an argument: `func enable_negative_edge(first_is_last : bool = false) -> Builder:`

**Comment by Pyxus** [comment] 2023-04-03 20:36
Sorry could you elaborate on what you're suggesting? I don't quite understand. Perhaps this is just a confusion caused by poor documentation relating to the feature... Negative edge allows you to match the final input with *either* a press or a release. But It does not enforce or require that the final input be a release. I can somewhat see where you're coming from with the reordering since the sequence is declared `"KP"` but negative edge, in a sense, makes it `"KPK^"`. but that's more of a "technical" change. By which I mean that in order to be release a button must first be pressed. However, the actual sequence is still just be "`PK`".

In games that utilize negative edge the general purpose is to allow for easier combo links. Imagine pressing `"P"` to punch an opponent followed by `"236P"` for Hadouken as your combo. With negative edge the combo becomes `"P -> 236 -> P^"`. Which can be performed a lot quicker than the standard route even if only by a few frames. Useful if the the hit stun of the punch isn't that long and you have to act quickly to sneak in the follow up.

**Comment by 20milliliter** [comment] 2023-04-03 20:57
Gotcha, after understanding how it works in the larger picture I no longer believe any change is needed.

This makes charged inputs the only unresolved topic in regards to this issue.

**Comment by Pyxus** [comment] 2023-08-16 03:06
The sequence matcher seems to be working fine based on my test. Better documentation is needed but otherwise I believe these problems are solved.

**Closed by Pyxus** 2023-08-16 03:06 UTC
